from btest.models import *

student1 = Students(surname='Иванов', name='Иван', patronymic='Иванович')
student1.save()
student2 = Students(surname='Петров', name='Петр', patronymic='Петрович')
student2.save()
student3 = Students(surname='Сидоров', name='Сидор', patronymic='Сидорович')
student3.save()
student4 = Students(surname='Алексеев', name='Алексей', patronymic='Алексеевич')
student4.save()
student5 = Students(surname='Федоров', name='Федор', patronymic='Федорович')
student5.save()
student6 = Students(surname='Михайлов', name='Михаил', patronymic='Михайлович')
student6.save()
student7 = Students(surname='Васильев', name='Василий', patronymic='Васильевич')
student7.save()
student8 = Students(surname='Николаев', name='Николай', patronymic='Николаевич')
student8.save()
student9 = Students(surname='Сергеев', name='Сергей', patronymic='Сергеевич')
student9.save()
student10 = Students(surname='Андреев', name='Андрей', patronymic='Андреевич')
student10.save()


subject1 = Subject(name='Алгебра', teacher='Норкина Анна Николаевна')
subject1.save()
subject2 = Subject(name='Геометрия', teacher='Смирнов Игорь Владимирович')
subject2.save()
subject3 = Subject(name='Физика', teacher='Кузнецова Елена Александровна')
subject3.save()
subject4 = Subject(name='Химия', teacher='Петрова Ольга Сергеевна')
subject4.save()
subject5 = Subject(name='Информатика', teacher='Морозов Дмитрий Андреевич')
subject5.save()